Repository icaropires/vandor-rename, pull requests merged in 2019-10, with the labels that each got.

#1 Add initial version, which can rename other students projects for corrections
  vandor-rename.sh
Labels: enhancement

#2 Change bash script to Python, adding new features!
  vandor-rename.py
  vandor-rename.sh
Labels: enhancement

#5 Add presentation of transformations to user and ask for confirmation
  vandor-rename.py
Labels: enhancement

#8 Complete readme
  README.md
  vandor-rename.py
Labels: documentation, enhancement

#13 Check user params
  README.md
  vandor-rename.py
Labels: enhancement

#14 Add feature of zipping the resulting files
  README.md
  vandor-rename.py
Labels: enhancement

#15 Resolves #19: Unit test framework and its coverage report
  .gitignore
  Makefile
  README.md
  requirements-dev.txt
  tests/__init__.py
  tests/test_vandor_rename.py
  vandor_rename.py
Labels: test

#20 More Tests
  .gitignore
  Makefile
  requirements-dev.txt
  tests/test_vandor_rename.py
Labels: test

#22 Add basic CI
  .travis.yml
  Makefile
  README.md
  requirements-dev.txt
Labels: enhancement
